# Generated by Django 4.0.5 on 2022-06-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0002_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('Text', models.TextField()),
                ('Created_Date', models.DateTimeField(auto_now_add=True)),
                ('Published_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
